const cfg = window.SUPABASE_CONFIG || {};
const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/svg+xml';favicon.href='favicon.svg?v=2';document.head.appendChild(favicon);
const db = window.supabase && cfg.url && !cfg.url.includes('YOUR-') ? window.supabase.createClient(cfg.url, cfg.anonKey) : null;
const adminStyle=document.createElement('style');adminStyle.textContent='.admin table button{font-family:inherit;font-weight:800;border:0;background:#d8ff3e;color:#111;padding:9px 13px;cursor:pointer}.admin table td:last-child{text-align:right;padding-right:10px}.admin table button.delete-player{background:transparent;color:#7f8981;font-size:14px;line-height:1;width:18px;height:18px;padding:0;margin-left:8px;opacity:.7;vertical-align:middle}.admin table button.delete-player:hover{background:transparent;color:#ff6d59;opacity:1;transform:none}.admin table button:hover{filter:brightness(1.08);transform:translateY(-1px)}.admin table button:disabled{opacity:.5;cursor:wait}';document.head.appendChild(adminStyle);
const teams = ['指挥分队','后勤分队','矛头分队','破坏战术分队','突击战术分队','堡垒战术分队','远程战术分队','高台突破分队','地面突破分队','本源研修分队','地质调查分队','文明开化分队','开拓者分队','多边贸易分队'];
const loginView=document.querySelector('#loginView'), panelView=document.querySelector('#panelView'), error=document.querySelector('#loginError'), body=document.querySelector('#playersBody'), notice=document.querySelector('#adminNotice');
document.querySelector('.admin table thead tr').innerHTML='<th>排名</th><th>姓名</th><th>QQ号</th><th>分队</th><th>比赛日期</th><th>报名时间</th><th>得分（可修改）</th><th>操作</th>';
document.querySelector('#loginButton').addEventListener('click',()=>{if(document.querySelector('#adminPassword').value===cfg.adminPassword){sessionStorage.setItem('is-admin','1');showPanel()}else error.textContent='密码不正确。'});
document.querySelector('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('is-admin');location.reload()}); document.querySelector('#refreshButton').addEventListener('click',loadPlayers);
function showPanel(){loginView.classList.add('hidden');panelView.classList.remove('hidden');loadPlayers()}
async function loadPlayers(){if(!db){notice.textContent='请先在 supabase-config.js 填入项目 URL 和 anon key。';body.innerHTML='';return} const {data,error:e}=await db.from('registrations').select('*').order('score',{ascending:false,nullsFirst:false}).order('created_at',{ascending:true});if(e){notice.textContent='读取失败：'+e.message;return}notice.textContent='';document.querySelector('#countLabel').textContent=`共 ${data.length} 名报名选手 · 按得分从高到低排列`;body.innerHTML=data.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.qq||'')}</td><td>${escapeHtml(p.team)}</td><td>${p.match_date}</td><td>${new Date(p.created_at).toLocaleString('zh-CN')}</td><td><input type="number" min="0" max="999" value="${p.score??''}" data-score="${p.id}"></td><td><button class="save-score" data-id="${p.id}">保存</button><button class="delete-player" title="删除此报名" aria-label="删除 ${escapeHtml(p.name)}" data-id="${p.id}" data-name="${escapeHtml(p.name)}">×</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">暂无报名记录</td></tr>';document.querySelectorAll('.save-score').forEach(b=>b.addEventListener('click',saveScore));document.querySelectorAll('.delete-player').forEach(b=>b.addEventListener('click',deletePlayer))}
async function saveScore(e){const id=e.currentTarget.dataset.id;const input=document.querySelector(`[data-score="${id}"]`);const score=input.value===''?null:Number(input.value);const {error:e2}=await db.from('registrations').update({score}).eq('id',id);notice.textContent=e2?'保存失败：'+e2.message:'得分已保存，列表正在重新排序。';if(!e2)loadPlayers()}
async function deletePlayer(e){const button=e.currentTarget;if(!window.confirm(`确定删除“${button.dataset.name}”的报名申请吗？此操作不可撤销。`))return;button.disabled=true;const {error:e2}=await db.from('registrations').delete().eq('id',button.dataset.id);notice.textContent=e2?'删除失败：'+e2.message:'报名申请已删除。';if(!e2)loadPlayers();else button.disabled=false}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if(sessionStorage.getItem('is-admin')==='1')showPanel();
