-- ============================================================
-- 报名表结构与行级安全策略（全新部署用）
-- ============================================================
-- 执行位置：Supabase 控制台 → SQL Editor
--
-- 安全模型（访问密码方案）：
--   管理后台采用「访问密码 + sessionStorage」的轻量验证，
--   前端始终以 anon 身份直连数据库，因此 anon 需要
--   insert / select / update / delete 四项权限。
--
--   请注意：anon key 按设计是公开密钥，会随前端下发到浏览器，
--   所以本表对任何访客都是可读可写的。表中存有报名者 QQ 号，
--   若日后需要真正的隔离，应改用 Supabase Auth 登录，
--   并把 select / update / delete 策略收窄到 authenticated。
--
--   访问密码本身存放在 supabase-config.js，
--   该文件已被 .gitignore 忽略，不要提交到版本库。
-- ============================================================

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 30),
  qq text not null check (char_length(qq) between 4 and 20),
  team text not null,
  match_date date not null check (match_date between date '2026-10-01' and date '2026-10-07'),
  score integer check (score is null or score between 0 and 999),
  created_at timestamptz not null default now()
);

alter table public.registrations enable row level security;

-- 报名端：提交报名（字段格式在策略层再校验一次）
create policy "报名者可以提交"
  on public.registrations for insert to anon
  with check (
    char_length(name) between 1 and 30
    and char_length(qq) between 4 and 20
    and match_date between date '2026-10-01' and date '2026-10-07'
  );

-- 公开得分榜与报名人数统计需要读取数据
create policy "报名者可以查看"
  on public.registrations for select to anon using (true);

-- 管理后台：修改得分
create policy "管理员可以修改得分"
  on public.registrations for update to anon
  using (true) with check (score is null or score between 0 and 999);

-- 管理后台：删除报名
create policy "管理员可以删除报名"
  on public.registrations for delete to anon using (true);
