-- ============================================================
-- 报名表结构与行级安全策略（全新部署用）
-- ============================================================
-- 执行位置：Supabase 控制台 → SQL Editor
-- 执行前请先在 Authentication → Users 中创建管理员账号，
-- 并在 Authentication → Providers → Email 中关闭公开注册。
--
-- 安全模型：
--   anon         只能提交报名；只能读取「已录入得分」记录的
--                name / team / score 三列（用于公开得分榜）
--   authenticated 管理员，可查看全部、改分、删除
-- ============================================================

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 30),
  qq text not null check (char_length(qq) between 4 and 20),
  team text not null,
  match_date date not null check (match_date between date '2026-10-01' and date '2026-10-07'),
  score integer check (score is null or score between 0 and 999),
  created_at timestamptz not null default now()
);

alter table public.registrations enable row level security;

-- 报名端：匿名用户只能提交报名，不能读取他人数据
create policy "报名者可以提交"
  on public.registrations for insert to anon
  with check (
    char_length(name) between 1 and 30
    and char_length(qq) between 4 and 20
    and match_date between date '2026-10-01' and date '2026-10-07'
  );

-- 公开得分榜：匿名仅能读取已录入得分的记录，
-- 列权限收窄到榜单实际需要的三列（不暴露 QQ 号与报名时间）
revoke select on public.registrations from anon;
grant select (name, team, score) on public.registrations to anon;

create policy "公榜可读已录入得分"
  on public.registrations for select to anon
  using (score is not null);

-- 管理端：仅已登录管理员可查看全部、修改得分、删除报名
create policy "管理员可以查看"
  on public.registrations for select to authenticated using (true);

create policy "管理员可以修改得分"
  on public.registrations for update to authenticated
  using (true) with check (score is null or score between 0 and 999);

create policy "管理员可以删除报名"
  on public.registrations for delete to authenticated using (true);

-- 报名人数统计改用安全定义函数，
-- 避免为了拿到总数而向匿名用户开放整表行读取
create or replace function public.registration_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.registrations; $$;

revoke all on function public.registration_count() from public;
grant execute on function public.registration_count() to anon, authenticated;
